student_management/account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    url(r'^$', views.profile, name="profile"),
    url(r'^login/$', auth_views.login,
        {'redirect_authenticated_user': True}, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),

]

student_management/result/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import views
from .views import StandardViewSet, MarksheetViewSet

router = routers.DefaultRouter()
router.register(r'marksheets', MarksheetViewSet)
router.register(r'standards', StandardViewSet)

urlpatterns = [
    url(r'^$', views.index,  name="index"),
    url(r'api/', include(router.urls)),

]

student_management/student_management/urls.py
from django.urls import re_path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^accounts/', include(('account.urls', 'account'), namespace='accounts')),
    re_path(r'^teachers/', include(('teachers.urls', 'teachers'), namespace='teachers')),
    re_path(r'^students/', include(('students.urls', 'students'), namespace='students')),
    re_path(r'^api-auth/', include(('rest_framework.urls', 'rest_framework'), namespace='rest_framework')),
    re_path(r'^', include(('result.urls', 'result'), namespace='result')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student_management/teacher/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name="teachers"),
    url(r'^marksheet/(?P<pk>\d+)/$',
        views.MarksheetDetailView.as_view(), name='marksheet-detail'),
    url(r'^marksheet/$', views.MarksheetListView.as_view(),
        name='marksheet-list'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^standard/$', views.standard, name='standard'),

]

student_management/result/models.py
from django.core.mail import EmailMessage
from django.core.validators import FileExtensionValidator
from django.urls import reverse
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from account.models import Profile

# Create your models here.


class Standard(models.Model):
    name = models.CharField(
        max_length=20, help_text='add Standard for ex. Standard 1')

    def __unicode__(self):
        return self.name


class Marksheet(models.Model):
    standard = models.ForeignKey(
        Standard, on_delete=models.CASCADE, help_text='Select Standard')
    uploaded_on = models.DateField(
        auto_now_add=True, help_text='File to Uploaded on')
    student_name = models.ForeignKey(
        Profile, related_name='marksheets', on_delete=models.CASCADE, help_text='Student Name')
    pdf_file = models.FileField(unique=True, upload_to='uploads/%Y/%m/%d/', default="Error to Showing file",
                                validators=[FileExtensionValidator(allowed_extensions=['pdf'])], help_text='Select file to upload.')

    class Meta:
        ordering = ['uploaded_on']

        def __unicode__(self):
            return self.student_name.user.username

    def __unicode__(self):
        return self.student_name.user.username

    def get_absolute_url(self):
        return reverse('students:marksheet-detail', kwargs={"pk": self.pk})


@receiver(post_save, sender=Marksheet)
def send_user_notification_callback(sender, **kwargs):
    """
    Callback for notifying student about marksheet.
    """
    instance = kwargs['instance']
    user = instance.student_name.user
    email = user.email
    pdf_url = instance.pdf_file.url

    html_content = "Welcome %s to Python School. Your Marksheet is available.\nYou can download it from your account or click the link below to dowload:\nhttp://localhost:8000{url}".format(
        url=pdf_url)

    message = EmailMessage(subject='welcome', body=html_content % (
        user), to=[email])
    message.content_subtype = 'html'
    message.send()

student_management/result/views.py
from django.shortcuts import render
from .serializers import StandardSerializer, MarksheetSerializer
from rest_framework import viewsets
from models import Marksheet, Standard

# Create your views here.


def index(request):
    if not request.user.is_authenticated:
        return render(request, "result/index.html")
    else:
        return render(request, "accounts/profile.html")


class MarksheetViewSet(viewsets.ModelViewSet):
    queryset = Marksheet.objects.all()
    serializer_class = MarksheetSerializer


class StandardViewSet(viewsets.ModelViewSet):
    queryset = Standard.objects.all()
    serializer_class = StandardSerializer

student_management/templates/result/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}Python School{% endblock %}</title>
  <meta charset="UTF-8" />
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>
<div id="page">
  <div id="header">
    <div id="section">
      <div class="logo">Python School</div>
      <span>python@schools.com <br />
      <br />
      + 91 90874 58904</span> </div>
    <ul class="nav-bottom">
      <li><a href="/">Home</a></li>
      {% if user.is_authenticated %}
        {%if user.is_staff or user.is_admin  %}
          <li><a href="{% url 'teachers:marksheet-list'  %}">Uploaded Marksheets</a></li>
          <li><a href="{% url 'teachers:teachers'  %}">Upload Marksheet</a></li>
          <li><a href="{% url 'teachers:standard'  %}">Add Standard</a></li>
         
        {% else %}
          <li><a href="{% url 'students:marksheet-list' %}">View Marksheet</a></li>
        {% endif%} 
        <li><a href="{% url 'accounts:logout'  %}">logout</a></li>
      {% else %}
        <li><a href="{% url 'accounts:login'  %}">login</a></li>
        <li><a href="{% url 'accounts:signup'  %}">Sign Up for Student</a></li>
        <li><a href="{% url 'teachers:signup'  %}">Sign Up for Teacher</a></li>

      {% endif %}
    </ul>
    
  </div>
  <div id="content">
    <div id="home">
        {% block content %}

        {% endblock %}
    </div>
  </div>
  <div id="footer">
    <div>
      <div id="connect"> <a href="#"><img src="{% static 'images/icon-facebook.gif' %}" alt="" /></a> <a href="#"><img src="{% static 'images/icon-twitter.gif' %}" alt="" /></a> <a href="#"><img src="{% static  'images/icon-youtube.gif' %}" alt="" /></a> </div>
      <div class="section">
        <ul>
          <li><a href="/">Home</a></li>
        </ul>
        <p>Copyright &copy; Python School</p>
      </div>
    </div>
  </div>
</div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
</html>

student_management/templates/result/index.html
{% extends 'result/base.html' %}
{% block title %}
	Python School
{% endblock %}
{% block content %}
	<div id="tagline">
	  <div class="welcome">
	  	<p>Welcome to Python School</p>
	  </div>	
      <div class="quote">
        <p>The joy of coding Python should be in seeing short, concise, readable classes that express a lot of action in a small amount of clear code -- not in reams of trivial code that bores the reader to death.</p>
		<p>- Guido van Rossum</p>
      </div>
    </div>
{% endblock %}

student_management/templates/result/marksheet_detail.html
{% extends 'result/base.html' %}
{% block title %} Marksheet | {{ marksheet }}{% endblock %}

{% block content %}


 <h2> Name: {{ marksheet.student_name.user.first_name }}</h2>
 <h2>Standard: {{ marksheet.standard }}</h2>
 <h2> Marksheet:</h2>

 <object data="{{ marksheet.pdf_file.url }}" type="application/pdf">
        <embed src="{{ marksheet.pdf_file.url }}" type="application/pdf" />
    </object>
   
{% endblock %}